// AI-центр — Этап 1 (аналитика без LLM). See CLAUDE.md / the accepted
// architecture spec for the full rationale: this layer only ever produces
// already-computed facts, never free-form LLM text. Stage 2 (narration)
// will consume these same DTOs unchanged — that's the whole point of
// keeping `facts`/`metrics` structured rather than a single opaque string.

export enum AiInsightCategory {
  MARGIN = "MARGIN",
  WRITE_OFF = "WRITE_OFF",
  SALES_ANOMALY = "SALES_ANOMALY",
  LOCATION_DEVIATION = "LOCATION_DEVIATION",
  RECEIVABLES = "RECEIVABLES",
  PAYABLES = "PAYABLES",
  CASH = "CASH",
  PRODUCTION = "PRODUCTION",
}

export const AI_INSIGHT_CATEGORY_LABELS_RU: Record<AiInsightCategory, string> = {
  [AiInsightCategory.MARGIN]: "Маржа",
  [AiInsightCategory.WRITE_OFF]: "Списания",
  [AiInsightCategory.SALES_ANOMALY]: "Продажи",
  [AiInsightCategory.LOCATION_DEVIATION]: "Сеть точек",
  [AiInsightCategory.RECEIVABLES]: "Дебиторская задолженность",
  [AiInsightCategory.PAYABLES]: "Кредиторская задолженность",
  [AiInsightCategory.CASH]: "Денежные средства",
  [AiInsightCategory.PRODUCTION]: "Производство",
};

export enum AiInsightPriority {
  CRITICAL = "CRITICAL",
  HIGH = "HIGH",
  MEDIUM = "MEDIUM",
  LOW = "LOW",
}

export const AI_INSIGHT_PRIORITY_LABELS_RU: Record<AiInsightPriority, string> = {
  [AiInsightPriority.CRITICAL]: "Критично",
  [AiInsightPriority.HIGH]: "Высокий",
  [AiInsightPriority.MEDIUM]: "Средний",
  [AiInsightPriority.LOW]: "Низкий",
};

// Used to sort the priority feed — highest first, matching the same
// pattern NotificationsService already uses for severity.
export const AI_INSIGHT_PRIORITY_WEIGHT: Record<AiInsightPriority, number> = {
  [AiInsightPriority.CRITICAL]: 3,
  [AiInsightPriority.HIGH]: 2,
  [AiInsightPriority.MEDIUM]: 1,
  [AiInsightPriority.LOW]: 0,
};

export enum AiConfidence {
  HIGH = "HIGH",
  MEDIUM = "MEDIUM",
  LOW = "LOW",
}

export const AI_CONFIDENCE_LABELS_RU: Record<AiConfidence, string> = {
  [AiConfidence.HIGH]: "Высокая уверенность",
  [AiConfidence.MEDIUM]: "Средняя уверенность",
  [AiConfidence.LOW]: "Недостаточно данных",
};

// One numeric fact behind an insight. Reserved verbatim as the exact
// payload a future AiNarrationService (Stage 2) would receive — never
// narrated by an LLM in Stage 1, since Stage 1 has no LLM at all.
export interface AiInsightMetricDto {
  label: string;
  value: number;
  unit: "money" | "percent" | "count" | "days";
}

export interface AiInsightDto {
  key: string;
  category: AiInsightCategory;
  priority: AiInsightPriority;
  confidence: AiConfidence;
  title: string;
  // Always present, always generated by code (template strings over
  // already-computed numbers) — never by an LLM. This is what Stage 1
  // shows instead of LLM narration.
  facts: string[];
  // A correlation the CODE found (e.g. a coincident ingredient price
  // change) — still not proven causation, always rendered separately and
  // caveated, never mixed into `facts`. Null when no such correlation was
  // found. Still zero LLM involvement in Stage 1 — this is a templated
  // string over two already-computed numbers, same as `facts`.
  hypothesis: string | null;
  metrics: AiInsightMetricDto[];
  locationId: string | null;
  locationName: string | null;
  link: string;
  createdAt: string;
}

export interface AiInsightsResponseDto {
  insights: AiInsightDto[];
}

export interface DismissAiInsightResponseDto {
  dismissed: true;
}

// ---- Executive summary (Сводка) ----

export interface AiExecutiveMetricDto {
  key: string;
  label: string;
  value: number;
  unit: "money" | "percent" | "count";
  // Null when there's no comparable previous period (e.g. a brand-new
  // organization) — the UI must show "нет данных для сравнения", never a
  // fabricated 0%/100% delta.
  deltaPct: number | null;
  confidence: AiConfidence;
}

export interface AiExecutiveSummaryDto {
  from: string;
  to: string;
  metrics: AiExecutiveMetricDto[];
}

// ---- Location deviation (Сравнение точек) ----

export interface AiLocationDeviationDto {
  locationId: string;
  locationName: string;
  revenue: number;
  averageTicket: number;
  expenses: number;
  lowStockCount: number;
  activeStaffCount: number;
  // Deviation from the network median for the same period, in percent.
  revenueDeviationPct: number;
  averageTicketDeviationPct: number;
  isOutlier: boolean;
  confidence: AiConfidence;
}

export interface AiLocationDeviationResponseDto {
  from: string;
  to: string;
  networkMedianRevenue: number;
  networkMedianAverageTicket: number;
  locations: AiLocationDeviationDto[];
}
