-- CreateEnum
CREATE TYPE "PnlTreatment" AS ENUM ('UNCLASSIFIED', 'OPERATING_EXPENSE', 'OTHER_INCOME', 'OTHER_EXPENSE', 'FINANCIAL_INCOME', 'FINANCIAL_EXPENSE', 'INCOME_TAX', 'NOT_IN_PNL');

-- CreateEnum
CREATE TYPE "CashActivity" AS ENUM ('UNCLASSIFIED', 'OPERATING', 'INVESTING', 'FINANCING');

-- CreateEnum
CREATE TYPE "BalanceTreatment" AS ENUM ('UNCLASSIFIED', 'NONE', 'FIXED_ASSET', 'OWNER_CONTRIBUTION', 'OWNER_WITHDRAWAL', 'LOAN_PROCEEDS', 'LOAN_REPAYMENT');

-- AlterTable
ALTER TABLE "finance_categories" ADD COLUMN     "balanceTreatment" "BalanceTreatment" NOT NULL DEFAULT 'UNCLASSIFIED',
ADD COLUMN     "cashActivity" "CashActivity" NOT NULL DEFAULT 'UNCLASSIFIED',
ADD COLUMN     "pnlTreatment" "PnlTreatment" NOT NULL DEFAULT 'UNCLASSIFIED';

